language: java
sudo: required
before_deploy:
- chmod 777 ./scripts/deploy.sh
deploy:
- provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_2df4b780ad7f_key -iv $encrypted_2df4b780ad7f_iv
  -in scripts/deploy.sh.enc -out scripts/deploy.sh -d
