language: java

sudo: required

before_deploy:
  - chmod 777 ./scripts/deploy.sh

deploy:
  - provider: script
    script: ./scripts/deploy.sh
    on:
      branch: master
    skip_cleanup: true
    
